### ISSUE TITLE
165Hz to 60Hz

### ISSUE THREAD

**Issue by ghost** [mohitbhatt-du/refresh_rate_fix_for_lig3#2]
i have the 165Hz model and this method was working for me. but recently i updated to windows 11 and it stopped working. still looking for a work around but no luck so far.

**Comment by mohitbhatt-du** [comment]
If the 60Hz option disappears after the update, you can redo the process. If the 60Hz option is still there but does not switch to 60Hz after selecting it, try removing the 60Hz configuration using CRU and create a new 60Hz configuration.

If you have tried the above solutions, please provide more information(screenshot if possible), and I will surely try to help you.
